@extends('layouts.app')
@php($ar=app()->getLocale()==='ar')
@section('title',$ar?'دليل الاستخدام':'Documentation')
@section('subtitle',$ar?'شرح استخدام MSA Go خطوة بخطوة':'MSA Go step-by-step user guide')
@section('content')
<div class="card docs-card"><h2>{{ $ar?'دليل استخدام MSA Go':'MSA Go User Guide' }}</h2>
@php($items=$ar?[['إنشاء رابط مختصر','اذهب إلى الروابط المختصرة ← رابط جديد. اكتب اسم الرابط ورابط الوجهة واختر رقمًا عشوائيًا أو Slug مخصصًا.','https://go.msa.edu.eg/516644'],['التتبع والرابط الكامل','اختر حملة أو الصق Full tracking URL. يدعم النظام كل قيم UTM بالإضافة إلى ref وbref وsem.','?utm_source=Facebook&utm_medium=Social&utm_campaign=Admission-2026&ref=facebook-story&sem=91'],['الحملات','الحملة تجمع الروابط وتوحد التقارير ويمكن إنشاؤها من صفحة Campaigns أو أثناء إنشاء الرابط.','Admissions 2026 — Facebook — Social'],['الحماية والحدود','من More options أضف كلمة مرور أو تاريخ انتهاء أو حدًا اختياريًا للزيارات.','Msa@2026 — 500 زيارة'],['الإحصائيات','تعرض Analytics الزيارات والزوار والأجهزة والمتصفحات والدول والمصادر مع تصدير CSV.','1,250 زيارة — 980 فريد — 270 متكرر'],['الوسوم والصلاحيات','Tags للتنظيم ولا تغير الرابط. المدير يدير المستخدمين والأدوار والصلاحيات.','Admissions / Facebook Campaign']]:[['Create a short link','Go to Short Links → New link. Enter name and destination, then choose a random 6-digit code or custom slug.','https://go.msa.edu.eg/516644'],['Tracking and full URL','Select a Campaign or paste Full tracking URL. Supports all UTM fields plus ref, bref and sem.','?utm_source=Facebook&utm_medium=Social&utm_campaign=Admission-2026&ref=facebook-story&sem=91'],['Campaigns','Campaigns group links and keep reporting consistent. Create them from Campaigns or while creating a link.','Admissions 2026 — Facebook — Social'],['Protection and limits','Under More options add a password, expiration or optional visit limit.','Msa@2026 — 500 visits'],['Analytics','Review visits, visitors, devices, browsers, countries and referrers; export CSV.','1,250 visits — 980 unique — 270 repeat'],['Tags and permissions','Tags organize links without changing URLs. Administrators manage users, roles and permissions.','Admissions / Facebook Campaign']])
@foreach($items as $i)<section><h3>{{ $i[0] }}</h3><p>{{ $i[1] }}</p><div class="example"><strong>{{ $ar?'مثال:':'Example:' }}</strong> <code>{{ $i[2] }}</code></div></section>@endforeach</div>
@push('head')<style>.docs-card{max-width:1000px;padding:28px}.docs-card h2,.docs-card h3{color:#072841}.docs-card section{border-bottom:1px solid var(--line);padding-bottom:20px;margin-bottom:22px}.docs-card p{color:var(--muted);line-height:1.8;font-size:13px}.example{background:#f3f7f4;border:1px solid #dbe7dd;border-radius:8px;padding:12px;color:#315e35;overflow:auto;font-size:12px}</style>@endpush
@endsection
