@extends('layouts.app')
@section('title', __('Short Links'))
@section('subtitle', __('Create, organize and monitor every branded link.'))
@section('content')
<div class="toolbar"><form class="search-form"><input class="input" type="search" name="search" value="{{ request('search') }}" placeholder="{{ __('Search by title, code or destination...') }}"><button class="button" type="submit">{{ __('Search') }}</button></form><span class="badge muted">{{ trans_choice(':count links', $links->total(), ['count'=>$links->total()]) }}</span></div>
<div class="card table-card"><div class="table-wrap"><table class="data-table"><thead><tr><th>{{ __('Link') }}</th><th>{{ __('Short URL') }}</th><th>{{ __('Type') }}</th><th>{{ __('Status') }}</th><th>{{ __('Created by') }}</th><th>{{ __('Visits') }}</th><th></th></tr></thead><tbody>
@forelse($links as $link)<tr><td><a class="link-title" href="{{ route('links.show',$link) }}">{{ $link->title ?: __('Untitled link') }}</a><span class="link-destination">{{ $link->destination_url }}</span></td><td><span class="short-url">{{ $link->short_url }}</span></td><td><span class="badge purple">{{ __($link->code_type === 'random' ? '6-digit code' : 'Custom slug') }}</span></td><td>@if(!$link->is_active)<span class="badge muted">{{ __('Inactive') }}</span>@elseif($link->expires_at?->isPast())<span class="badge warning">{{ __('Expired') }}</span>@else<span class="badge success">{{ __('Active') }}</span>@endif</td><td>{{ $link->creator?->name }}<span class="link-destination">{{ $link->created_at->format('M d, Y') }}</span></td><td><strong>{{ number_format($link->visits_count) }}</strong></td><td><div class="actions"><button class="button small" data-copy="{{ $link->short_url }}">{{ __('Copy') }}</button><a class="button small" href="{{ route('links.show',$link) }}">{{ __('View') }}</a>@can('links.update')<a class="button small" href="{{ route('links.edit',$link) }}">{{ __('Edit') }}</a>@endcan</div></td></tr>
@empty<tr><td colspan="7"><div class="empty-state"><strong>{{ __('No links found') }}</strong>{{ __('Create your first short link or adjust your search.') }}</div></td></tr>@endforelse
</tbody></table></div>@if($links->hasPages())<div class="pagination">@if($links->onFirstPage())<span>‹</span>@else<a href="{{ $links->previousPageUrl() }}">‹</a>@endif<span class="active">{{ $links->currentPage() }}</span>@if($links->hasMorePages())<a href="{{ $links->nextPageUrl() }}">›</a>@endif</div>@endif</div>
@endsection
