@extends('layouts.app')
@section('title', $link->title ?: __('Untitled link'))
@section('subtitle', __('Created :date by :name', ['date'=>$link->created_at->format('M d, Y · H:i'),'name'=>$link->creator?->name]))
@section('content')
<div class="detail-grid"><div class="card"><div class="card-header"><div><h2>{{ __('Short link') }}</h2><p>{{ __('Share this URL in campaigns, messages and printed materials.') }}</p></div><div class="actions">@can('links.update')<a class="button" href="{{ route('links.edit',$link) }}">{{ __('Edit') }}</a>@endcan</div></div><div class="card-body">
    <div class="detail-url"><code>{{ $link->short_url }}</code><button class="button primary" data-copy="{{ $link->short_url }}">{{ __('Copy link') }}</button></div>
    <div class="actions" style="margin-top:12px"><a class="button small" href="{{ route('links.qr', [$link, 'png']) }}">{{ __('Download QR PNG') }}</a><a class="button small" href="{{ route('links.qr', [$link, 'svg']) }}">{{ __('Download QR SVG') }}</a>@can('links.update')<a class="button small" href="{{ route('links.smart-targets.index', $link) }}">{{ __('Smart redirects') }}</a>@endcan</div>
    <label class="field"><span>{{ __('Destination URL') }}</span><div class="detail-url"><code style="color:var(--text);font-size:12px">{{ $link->destination_url }}</code><a class="button small" href="{{ $link->destination_url }}" target="_blank" rel="noopener">↗</a></div></label>
    <div class="meta-list"><div class="meta-item"><span>{{ __('Status') }}</span><strong>{{ $link->is_active ? __('Active') : __('Inactive') }}</strong></div><div class="meta-item"><span>{{ __('Code type') }}</span><strong>{{ __($link->code_type === 'random' ? '6-digit code' : 'Custom slug') }}</strong></div><div class="meta-item"><span>{{ __('Campaign') }}</span><strong>{{ $link->campaign?->name ?? '—' }}</strong></div><div class="meta-item"><span>{{ __('Tags') }}</span><strong>{{ $link->tags->pluck('name')->join(', ') ?: '—' }}</strong></div><div class="meta-item"><span>{{ __('Health') }}</span><strong>{{ $link->health_status ?? __('Not checked') }}{{ $link->last_status_code ? ' · '.$link->last_status_code : '' }}</strong></div><div class="meta-item"><span>{{ __('Expiration') }}</span><strong>{{ $link->expires_at?->format('M d, Y · H:i') ?? __('Never') }}</strong></div><div class="meta-item"><span>{{ __('Last updated by') }}</span><strong>{{ $link->updater?->name ?? '—' }}</strong></div></div>
    <div class="form-footer">@can('links.update')<form method="POST" action="{{ route('links.toggle',$link) }}">@csrf @method('PATCH')<button class="button" type="submit">{{ $link->is_active ? __('Deactivate') : __('Activate') }}</button></form>@endcan @can('links.delete')<form method="POST" action="{{ route('links.destroy',$link) }}" onsubmit="return confirm(@js(__('Archive this link?')))" >@csrf @method('DELETE')<button class="button danger" type="submit">{{ __('Archive') }}</button></form>@endcan</div>
</div></div>
<div><div class="stat-card" style="margin-bottom:20px"><div class="stat-label"><span>{{ __('Total visits') }}</span><span class="stat-icon">⌁</span></div><div class="stat-value">{{ number_format($link->visits_count) }}</div><a class="button primary full" href="{{ route('analytics.link',$link) }}">{{ __('Open detailed analytics') }}</a></div><div class="card"><div class="card-header"><h2>{{ __('Ownership') }}</h2></div><div class="card-body meta-list" style="grid-template-columns:1fr"><div class="meta-item"><span>{{ __('Created by') }}</span><strong>{{ $link->creator?->name }}</strong></div><div class="meta-item"><span>{{ __('Created at') }}</span><strong>{{ $link->created_at->format('M d, Y · H:i') }}</strong></div><div class="meta-item"><span>{{ __('Updated at') }}</span><strong>{{ $link->updated_at->format('M d, Y · H:i') }}</strong></div></div></div></div></div>
@endsection
