@extends('layouts.app')
@section('title', __('Analytics'))
@section('subtitle', __('Understand visits, audiences, devices and traffic sources.'))
@section('content')
<div class="card" style="margin-bottom:18px"><div class="card-body"><form class="filter-row"><label class="field"><span>{{ __('Date range') }}</span><select name="days"><option value="7" @selected($days===7)>{{ __('Last 7 days') }}</option><option value="30" @selected($days===30)>{{ __('Last 30 days') }}</option><option value="90" @selected($days===90)>{{ __('Last 90 days') }}</option></select></label><label class="field" style="min-width:260px"><span>{{ __('Short link') }}</span><select name="link_id"><option value="">{{ __('All links') }}</option>@foreach($links as $link)<option value="{{ $link->id }}" @selected((string)$selectedLink===(string)$link->id)>{{ $link->title ?: $link->code }} · /{{ $link->code }}</option>@endforeach</select></label><button class="button primary" type="submit">{{ __('Apply filters') }}</button><a class="button" href="{{ route('exports.links') }}">{{ __('Export links CSV') }}</a><a class="button" href="{{ route('exports.visits') }}">{{ __('Export visits CSV') }}</a></form></div></div>
<div class="stats-grid" style="grid-template-columns:repeat(3,1fr)"><div class="stat-card"><div class="stat-label"><span>{{ __('Visits') }}</span><span class="stat-icon">⌁</span></div><div class="stat-value">{{ number_format($visits) }}</div><div class="stat-hint">{{ trans_choice('Across :count days', $days, ['count'=>$days]) }}</div></div><div class="stat-card"><div class="stat-label"><span>{{ __('Unique visitors') }}</span><span class="stat-icon">◎</span></div><div class="stat-value">{{ number_format($unique) }}</div><div class="stat-hint">{{ __('Bots excluded') }}</div></div><div class="stat-card"><div class="stat-label"><span>{{ __('Repeat visits') }}</span><span class="stat-icon">↻</span></div><div class="stat-value">{{ number_format(max(0,$visits-$unique)) }}</div><div class="stat-hint">{{ __('Visits beyond the first visit') }}</div></div></div>
<div class="card" style="margin-bottom:20px"><div class="card-header"><div><h2>{{ __('Traffic over time') }}</h2><p>{{ __('Total and unique visits for the selected period') }}</p></div></div><div class="card-body"><div class="chart-box"><canvas id="analyticsChart"></canvas></div></div></div>
<div class="dashboard-grid"><div class="card"><div class="card-header"><h2>{{ __('Devices & platforms') }}</h2></div><div class="card-body"><div class="dashboard-grid" style="grid-template-columns:1fr 1fr;margin:0"><div><h3 style="font-size:11px">{{ __('Devices') }}</h3>@foreach($devices as $row)<div class="mini-row"><div class="grow"><strong>{{ __($row->device_type ?? 'Unknown') }}</strong></div><span class="metric">{{ number_format($row->total) }}</span></div>@endforeach</div><div><h3 style="font-size:11px">{{ __('Platforms') }}</h3>@foreach($platforms as $row)<div class="mini-row"><div class="grow"><strong>{{ $row->platform ?? __('Unknown') }}</strong></div><span class="metric">{{ number_format($row->total) }}</span></div>@endforeach</div></div></div></div><div class="card"><div class="card-header"><h2>{{ __('Browsers') }}</h2></div><div class="card-body mini-list">@forelse($browsers as $row)<div class="mini-row"><span class="dot"></span><div class="grow"><strong>{{ $row->browser ?? __('Unknown') }}</strong></div><span class="metric">{{ number_format($row->total) }}</span></div>@empty<div class="empty-state">{{ __('No visit data yet.') }}</div>@endforelse</div></div><div class="card"><div class="card-header"><h2>{{ __('Countries') }}</h2></div><div class="card-body mini-list">@forelse($countries as $row)<div class="mini-row"><span class="dot"></span><div class="grow"><strong>{{ $row->country ?? __('Unknown') }}</strong></div><span class="metric">{{ number_format($row->total) }}</span></div>@empty<div class="empty-state">{{ __('Country data appears when your proxy/CDN sends location headers.') }}</div>@endforelse</div></div></div>
<div class="card"><div class="card-header"><h2>{{ __('Traffic sources') }}</h2></div><div class="table-wrap"><table class="data-table"><thead><tr><th>{{ __('Referrer') }}</th><th>{{ __('Visits') }}</th></tr></thead><tbody>@forelse($referrers as $row)<tr><td>{{ $row->referer_host ?: __('Direct / unknown') }}</td><td>{{ number_format($row->total) }}</td></tr>@empty<tr><td colspan="2"><div class="empty-state">{{ __('No referrer data yet.') }}</div></td></tr>@endforelse</tbody></table></div></div>
@endsection
@push('scripts')<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.9/dist/chart.umd.min.js"></script><script>const d=@json($daily);new Chart(document.getElementById('analyticsChart'),{type:'line',data:{labels:d.map(x=>x.day),datasets:[{label:@json(__('Visits')),data:d.map(x=>x.total),borderColor:'#072841',backgroundColor:'rgba(7,40,65,.1)',fill:true,tension:.35,pointRadius:1},{label:@json(__('Unique')),data:d.map(x=>x.unique),borderColor:'#538F3F',tension:.35,pointRadius:1}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'bottom'}},scales:{x:{grid:{display:false},ticks:{maxTicksLimit:15,font:{size:9}}},y:{beginAtZero:true,ticks:{precision:0}}}}});</script>@endpush
