@extends('layouts.app')

@section('title', __('Exhibition contacts'))
@section('subtitle', __('Business-card contacts are stored separately from student registrations.'))

@section('content')
<div class="toolbar"><div></div><div class="top-actions"><a class="button" href="{{ route('crm.event-contact-tags.index') }}">{{ __('Manage tags') }}</a>@can('crm.event_contacts.manage')<a class="button primary" href="{{ route('crm.event-contacts.create') }}">＋ {{ __('Add contact') }}</a>@endcan</div></div>
<div class="card filter-card"><div class="card-body"><form class="filter-row" method="GET">
    <label class="field"><span>{{ __('Search') }}</span><input name="search" value="{{ request('search') }}" placeholder="{{ __('Name, email or phone') }}"></label>
    <label class="field"><span>{{ __('Exhibition') }}</span><select name="event"><option value="">{{ __('All exhibitions') }}</option>@foreach($events as $event)<option value="{{ $event }}" @selected(request('event') === $event)>{{ __($event) }}</option>@endforeach</select></label>
    <div class="field tag-filter"><span>{{ __('Tags') }}</span><details class="multi-filter"><summary>{{ count((array) request('tag_ids', [])) ? trans_choice(':count selected', count((array) request('tag_ids', [])), ['count' => count((array) request('tag_ids', []))]) : __('All tags') }} <b>⌄</b></summary><div>@forelse($tags as $tag)<label><input type="checkbox" name="tag_ids[]" value="{{ $tag->id }}" @checked(in_array((string) $tag->id, (array) request('tag_ids', []), true))><i style="background:{{ $tag->color }}"></i><span>{{ $tag->name }}</span><small>{{ $tag->contacts_count }}</small></label>@empty<span class="empty-filter">{{ __('No tags yet') }}</span>@endforelse</div></details></div>
    <label class="field"><span>{{ __('Status') }}</span><select name="status"><option value="">{{ __('All statuses') }}</option>@foreach(\App\Models\EventContact::STATUSES as $status)<option value="{{ $status }}" @selected(request('status') === $status)>{{ __(ucfirst($status)) }}</option>@endforeach</select></label>
    <button class="button primary" type="submit">{{ __('Apply filters') }}</button>@if(request()->hasAny(['search','event','status','tag_ids']))<a class="button" href="{{ route('crm.event-contacts.index') }}">{{ __('Clear') }}</a>@endif
</form></div></div>
<div class="card table-card event-contacts-table"><div class="table-wrap"><table class="data-table">
    <thead><tr><th>{{ __('Name') }}</th><th>{{ __('Emails') }}</th><th>{{ __('Phone numbers') }}</th><th>{{ __('Exhibition') }}</th><th>{{ __('Source') }}</th><th>{{ __('Status') }}</th><th>{{ __('Actions') }}</th></tr></thead>
    <tbody>@forelse($contacts as $contact)<tr>
        <td><strong>{{ $contact->name }}</strong>@if($contact->tags->isNotEmpty())<div class="contact-tags">@foreach($contact->tags as $tag)<span style="--tag-color:{{ $tag->color }}"><i></i>{{ $tag->name }}</span>@endforeach</div>@endif</td>
        <td>@foreach($contact->emails as $email)<a class="contact-email" href="mailto:{{ $email }}" dir="ltr">{{ $email }}</a>@endforeach</td>
        <td>@forelse($contact->phones ?? [] as $phone)<a class="contact-phone" href="tel:{{ preg_replace('/[^0-9+]/', '', $phone) }}" dir="ltr">{{ $phone }}</a>@empty<span class="muted-text">{{ __('Not provided') }}</span>@endforelse</td>
        <td>{{ __($contact->event_name) }}</td><td>{{ __(ucwords(str_replace('_', ' ', $contact->source))) }}</td>
        <td><span class="badge {{ $contact->status === 'new' ? 'warning' : ($contact->status === 'qualified' ? 'success' : 'purple') }}">{{ __(ucfirst($contact->status)) }}</span></td>
        <td><div class="row-actions"><a class="button small" href="{{ route('crm.event-contacts.show', $contact) }}">{{ __('View') }}</a>@can('crm.event_contacts.manage')<a class="button small" href="{{ route('crm.event-contacts.edit', $contact) }}">{{ __('Edit') }}</a><form method="POST" action="{{ route('crm.event-contacts.destroy', $contact) }}" onsubmit="return confirm(@js(__('Are you sure you want to delete this contact?')))" >@csrf @method('DELETE')<button class="button small danger" type="submit">{{ __('Delete') }}</button></form>@endcan</div></td>
    </tr>@empty<tr><td colspan="7"><div class="empty-state"><strong>{{ __('No exhibition contacts found') }}</strong></div></td></tr>@endforelse</tbody>
</table></div>{{ $contacts->onEachSide(1)->links('pagination.msa') }}</div>
@endsection

@push('head')<style>.filter-card{margin-bottom:18px}.filter-row .field:first-child{flex:1;min-width:220px}.contact-email,.contact-phone{display:block;color:#3f7032;margin:3px 0;white-space:nowrap}.row-actions{display:flex;align-items:center;justify-content:flex-end;gap:6px}.row-actions form{margin:0}.tag-filter{min-width:190px}.multi-filter{position:relative}.multi-filter summary{list-style:none;display:flex;justify-content:space-between;gap:12px;border:1px solid #dfe4eb;border-radius:10px;padding:11px 13px;background:#fff;cursor:pointer;font-size:12px}.multi-filter summary::-webkit-details-marker{display:none}.multi-filter[open] summary{border-color:#538f3f}.multi-filter>div{position:absolute;z-index:30;top:calc(100% + 5px);inset-inline:0;min-width:230px;max-height:260px;overflow:auto;padding:7px;background:#fff;border:1px solid var(--line);border-radius:10px;box-shadow:0 12px 28px rgba(7,40,65,.15)}.multi-filter label{display:flex;align-items:center;gap:8px;padding:8px;border-radius:7px;cursor:pointer}.multi-filter label:hover,.multi-filter label:has(input:checked){background:#edf5ea}.multi-filter input{width:auto}.multi-filter i,.contact-tags i{width:8px;height:8px;border-radius:50%;flex:none}.multi-filter small{margin-inline-start:auto}.empty-filter{display:block;padding:9px;color:var(--muted)}.contact-tags{display:flex;flex-wrap:wrap;gap:4px;margin-top:6px}.contact-tags span{display:flex;align-items:center;gap:4px;padding:3px 6px;border-radius:10px;background:#f2f5f3;font-size:8px;color:#52615a}.contact-tags i{background:var(--tag-color)}@media(max-width:900px){.filter-row{align-items:stretch}.filter-row .field,.filter-row .button{width:100%}}</style>@endpush
