@extends('layouts.partner')
@php($editing = $referral->exists)
@section('title', $editing ? __('Edit student') : __('Register a student'))
@section('content')
<div class="partner-page-head"><div><h1>{{ $editing ? __('Edit student details') : __('Register a student') }}</h1><p>{{ $editing ? __('Update the student details before the application is reviewed.') : __('Enter the student details to start follow-up with MSA.') }}</p></div><a class="button ghost" href="{{ route('partner.referrals.index') }}">{{ __('Back to my students') }}</a></div>
<form class="partner-form" method="POST" action="{{ $editing ? route('partner.referrals.update', $referral) : route('partner.referrals.store') }}" enctype="multipart/form-data">@csrf @if($editing) @method('PUT') @endif
<section class="form-section partner-card"><div class="form-section-head"><span class="section-number">1</span><div><h2>{{ __('Student details') }}</h2><p>{{ __('Only a few details are needed.') }}</p></div></div><div class="form-section-body"><div class="form-grid"><label class="field full"><span>{{ __('Student full name') }} <b class="required">*</b></span><input name="student_name" value="{{ old('student_name', $referral->student_name) }}" required maxlength="255" autocomplete="name"></label><label class="field"><span>{{ __('Mobile / WhatsApp') }} <b class="required">*</b></span><input type="tel" name="mobile" value="{{ old('mobile', $referral->mobile) }}" required inputmode="tel" autocomplete="tel"></label><label class="field"><span>{{ __('Student email') }} <small>({{ __('Optional') }})</small></span><input type="email" name="email" value="{{ old('email', $referral->email) }}" autocomplete="email"></label><label class="field"><span>{{ __('Nationality') }} <b class="required">*</b></span><select name="nationality" required><option value="">{{ __('Choose a country') }}</option>@foreach(\App\Models\StudentReferral::COUNTRIES as $country)<option value="{{ $country }}" @selected(old('nationality', $referral->nationality) === $country)>{{ __($country) }}</option>@endforeach</select></label><label class="field"><span>{{ __('Requested faculty / program') }} <b class="required">*</b></span><select name="desired_program" required><option value="">{{ __('Choose a program') }}</option>@foreach(\App\Models\StudentReferral::PROGRAMS as $program)<option value="{{ $program }}" @selected(old('desired_program', $referral->desired_program) === $program)>{{ __($program) }}</option>@endforeach</select></label></div></div></section>
<section class="form-section partner-card"><div class="form-section-head"><span class="section-number">2</span><div><h2>{{ __('Passport copy') }}</h2><p>{{ __('Optional — you can provide it later.') }}</p></div></div><div class="form-section-body"><label class="field full"><span>{{ $editing && $referral->passport_path ? __('Replace passport copy') : __('Passport copy') }}</span><input type="file" name="passport" accept=".jpg,.jpeg,.png,.pdf"><small>{{ __('JPG, PNG or PDF, up to 5 MB.') }}</small></label></div></section>
<div class="submit-panel"><div><label class="checkbox"><input type="checkbox" name="consent" value="1" @checked(old('consent', $referral->consent)) required><span>{{ __('I confirm that the student agreed to share these details with MSA University for admission follow-up.') }} <b class="required">*</b></span></label><p>{{ __('Your partner name and the submission time are recorded automatically.') }}</p></div><button class="button primary" type="submit">{{ $editing ? __('Save changes') : __('Register student') }}</button></div></form>
@endsection
