<!doctype html>
<html lang="{{ app()->getLocale() }}" dir="{{ app()->getLocale() === 'ar' ? 'rtl' : 'ltr' }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta name="robots" content="noindex, nofollow">
    <title>@yield('title') · MSA University</title>
    <link rel="icon" href="{{ asset('images/msa-logo.png') }}" type="image/png">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Tajawal:wght@400;500;700;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('css/app.css') }}"><link rel="stylesheet" href="{{ asset('css/brand.css') }}">
    <style>body{background:#f3f6f4}.partner-header{background:#072841;color:#fff}.partner-header-inner{max-width:1060px;margin:auto;padding:18px 24px;display:flex;align-items:center;justify-content:space-between;gap:18px}.partner-brand{display:flex;align-items:center;gap:14px;color:#fff}.partner-brand img{width:145px;filter:brightness(0) invert(1)}.partner-brand small{display:block;color:rgba(255,255,255,.65);font-size:11px}.partner-actions{display:flex;align-items:center;gap:12px}.partner-actions form{margin:0}.partner-logout{color:#fff;border-color:rgba(255,255,255,.35);background:transparent}.partner-main{max-width:1060px;margin:0 auto;padding:38px 24px 70px}.partner-page-head{display:flex;align-items:end;justify-content:space-between;gap:20px;margin-bottom:24px}.partner-page-head h1{font-size:28px;letter-spacing:-.035em;margin:0 0 5px}.partner-page-head p{color:#68777f;margin:0;font-size:13px}.partner-card{background:#fff;border:1px solid #e1e8e3;border-radius:17px;box-shadow:0 6px 22px rgba(7,40,65,.04)}.partner-form{max-width:760px}.partner-form .form-section{margin-bottom:18px}.partner-form .form-section-head{padding:20px 24px;border-bottom:1px solid #e8ede9;display:flex;gap:14px}.partner-form .form-section-body{padding:24px}.partner-form .form-grid{gap:20px}.partner-form .submit-panel{background:#072841;color:#fff;border-radius:17px;padding:25px;display:flex;justify-content:space-between;align-items:center;gap:20px}.partner-form .submit-panel p{color:rgba(255,255,255,.7);font-size:11px;margin:5px 0 0}.section-number{display:grid;place-items:center;width:31px;height:31px;border-radius:9px;background:#edf5ea;color:#3f7032;font-weight:800;flex:0 0 auto}.form-section-head h2{font-size:16px;margin:0 0 4px}.form-section-head p{font-size:11px;color:#68777f;margin:0}.required{color:#b43d3d}.field input[type=file]{padding:10px}.link-destination{display:block;margin-top:4px}.status-pill{display:inline-block;padding:5px 9px;border-radius:8px;background:#edf5ea;color:#3f7032;font-size:11px;font-weight:700}.status-pill.incomplete{background:#fff4dc;color:#936313}.status-pill.contacted{background:#eaf2fb;color:#235e98}.status-pill.enrolled{background:#e7f5ea;color:#27733c}@media(max-width:650px){.partner-header-inner,.partner-page-head{align-items:stretch;flex-direction:column}.partner-page-head .button{width:100%}.partner-main{padding-top:26px}.partner-form .submit-panel{align-items:stretch;flex-direction:column}.partner-form .submit-panel .button{width:100%}}</style>
    <style>.partner-language{display:inline-flex;align-items:center;gap:7px;min-height:38px;padding:0 12px;border:1px solid rgba(255,255,255,.45);border-radius:10px;background:rgba(255,255,255,.08);color:#fff;font-size:12px;font-weight:700}.partner-language:hover{background:rgba(255,255,255,.16)}@media(max-width:650px){.partner-actions{flex-wrap:wrap}}</style>
    @stack('head')
</head>
<body><header class="partner-header"><div class="partner-header-inner"><a class="partner-brand" href="{{ route('partner.referrals.index') }}"><img src="{{ asset('images/msa-logo-wide.png') }}" alt="MSA University"><span><strong>{{ auth()->user()->recruitmentPartner->name }}</strong><small>{{ __('Partner portal') }}</small></span></a><div class="partner-actions"><a class="button small partner-logout" href="{{ route('partner.profile.edit') }}">{{ __('My profile') }}</a><a class="partner-language" href="{{ route('locale', app()->getLocale() === 'ar' ? 'en' : 'ar') }}" aria-label="{{ __('Change language') }}">🌐 <span>{{ app()->getLocale() === 'ar' ? 'English' : 'العربية' }}</span></a><form method="POST" action="{{ route('partner.logout') }}">@csrf<button class="button small partner-logout" type="submit">{{ __('Sign out') }}</button></form></div></div></header><main class="partner-main">@if(session('success'))<div class="alert success">✓ {{ session('success') }}</div>@endif @if($errors->any())<div class="alert danger"><strong>{{ __('Please fix the following errors:') }}</strong><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif @yield('content')</main></body>
</html>
